# Generated by Django 3.2.5 on 2021-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(null=True),
        ),
    ]
